# Generated by Django 5.0.7 on 2024-07-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Должность исполнителя',
                'verbose_name_plural': 'Должности исполнителей',
            },
        ),
    ]
