name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # - name: List files for debugging
    #   run: |
    #     ls -la
    #     ls -la Home_button

    # - name: Run tests
    #   env:
    #     DJANGO_SETTINGS_MODULE: Home_button.Home_button.settings
    #     DATABASE_URL: postgres://postgres:postgres@localhost/test_db
    #   run: |
    #     cd Home_button
    #     source ../venv/bin/activate
    #     python manage.py migrate
    #     pytest
